"""fix name column in table hotels

Revision ID: 0e6ecea25306
Revises: 93169a8e1b3a
Create Date: 2025-01-31 14:09:06.781183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e6ecea25306'
down_revision: Union[str, None] = '93169a8e1b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('hotels', 'servicces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('servicces', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'services')
    # ### end Alembic commands ###
